import type { ProjectGalleryView } from "./content";

/** Authentic source-page captures taken on 6 October 2026; original pixels retained. */
export const lexpoGallery: readonly ProjectGalleryView[] = [
  {
    image: "/images/lexpo/home.jpg",
    fullImage: "/images/lexpo/home-full.jpg",
    imageWidth: 1165,
    imageHeight: 747,
    title: "Accueil et découverte",
    titleEn: "Home and discovery",
    imageAlt: "Accueil L’Expo : titre, recherche de créations et invitation à créer sa vitrine",
    imageAltEn: "L’Expo homepage with headline, creation search and storefront invitation",
    caption: "Une entrée centrée sur le savoir-faire et la recherche de créations. La capture complète comprend les sections de présentation et les artisans mis en avant.",
    captionEn: "An introduction focused on craftsmanship and finding creations. The full-page screenshot includes the presentation sections and featured artisans.",
    sourceUrl: "https://lexpo-gallery.vercel.app/",
  },
  {
    image: "/images/lexpo/explorer-mode-lin.jpg",
    imageWidth: 1165,
    imageHeight: 909,
    title: "Explorer les créations",
    titleEn: "Browse creations",
    imageAlt: "Explorateur L’Expo avec le filtre Mode & Lin actif et trois cartes de créations",
    imageAltEn: "L’Expo explorer with the Mode & Lin filter active and three creation cards",
    caption: "Recherche, catégories et cartes produits. Vue capturée avec le filtre « Mode & Lin » actif ; les textes et les photos du site source sont conservés tels quels.",
    captionEn: "Search, categories and product cards. Captured with the “Mode & Lin” filter active; source-site text and photos are preserved as displayed.",
    sourceUrl: "https://lexpo-gallery.vercel.app/explorer",
  },
  {
    image: "/images/lexpo/artisans.jpg",
    fullImage: "/images/lexpo/artisans-full.jpg",
    imageWidth: 1165,
    imageHeight: 747,
    title: "L’annuaire des artisans",
    titleEn: "The artisan directory",
    imageAlt: "Annuaire L’Expo avec recherche, filtres par métier et cartes de profils artisans",
    imageAltEn: "L’Expo directory with search, craft filters and artisan profile cards",
    caption: "Un aperçu des talents, de leurs métiers et de leurs villes, avec une recherche et des filtres pour parcourir l’annuaire.",
    captionEn: "An overview of artisans, their crafts and cities, with search and filters for browsing the directory.",
    sourceUrl: "https://lexpo-gallery.vercel.app/artisans",
  },
  {
    image: "/images/lexpo/dashboard.jpg",
    imageWidth: 1165,
    imageHeight: 747,
    title: "Le tableau de bord artisan",
    titleEn: "The artisan dashboard",
    imageAlt: "Aperçu du dashboard L’Expo : navigation latérale, indicateurs, profil à compléter et état sans création",
    imageAltEn: "L’Expo dashboard overview with sidebar, metrics, incomplete profile notice and empty creations state",
    caption: "Navigation latérale, aperçu de la vitrine et invitation à compléter le profil. Les indicateurs affichés appartiennent à l’interface source et sont non vérifiés.",
    captionEn: "Sidebar navigation, storefront overview and an invitation to complete the profile. The displayed metrics belong to the source interface and are not verified.",
    sourceUrl: "https://lexpo-gallery.vercel.app/dashboard",
  },
  {
    image: "/images/lexpo/dashboard-plans.jpg",
    imageWidth: 1165,
    imageHeight: 1099,
    title: "Les formules d’abonnement",
    titleEn: "Subscription plans",
    imageAlt: "Onglet Mon Abonnement du dashboard L’Expo avec les trois formules Artisan Découverte, Pro et Élite",
    imageAltEn: "L’Expo dashboard subscription tab with the three Artisan Découverte, Pro and Élite plans",
    caption: "Vue complète de l’onglet « Mon Abonnement ». Les prix et les avantages sont ceux affichés le 6 octobre 2026 ; aucun parcours de paiement n’a été testé.",
    captionEn: "Full view of the “Mon Abonnement” tab. Prices and benefits are those displayed on 6 October 2026; the payment flow was not tested.",
    sourceUrl: "https://lexpo-gallery.vercel.app/dashboard",
  },
];
